#:schedule:
#  update_start:
#    cron: '0 0 3 * * * Europe/Warsaw'
#    class: AppointmentUpdateBatch
#  query_mailer:
#    cron: '0 0 9 * * * Europe/Warsaw'
#    class: QueryMailerWorker

:queues:
  
  - critical
  - default
  - low
  - mailers